### ISSUE TITLE
[Proposal] Supporting arch other than x86_64 or amd64 (with how)

### ISSUE THREAD

**Issue by seia-soto** [Jigsaw-Code/outline-server#1039]
Hello? I recently created a simple script that builds multi-platform supported docker image of shadowbox (or outline-server).
During building the script, I got some clean ways to build multi-platform shadowbox image even there is directory called `third_party` which is platform-sensitive.

## Using Docker BuildKit's `$TARGETPLATFORM`

Thanks to Docker BuildKit's `TARGETPLATFORM` argument in `Dockerfile`, we can use it in `COPY` command inside of `Dockerfile`.

Like following snippet:

```dockerfile
ARG TARGETPLATFORM
RUN mkdir -p third_party
COPY third_party/outline-ss-server/${TARGETPLATFORM} third_party/outline-ss-server
COPY third_party/prometheus/${TARGETPLATFORM} third_party/prometheus
```

> Note that ARG has scoping issue, so we need to put it after `FROM` keyword.

Following to above, we can expect paths like `third_party/${TARGETPLATFORM}`:

- third_party/linux/arm64
- third_party/linux/amd64
- third_party/linux/arm/v7
- third_party/linux/arm/v6
- ...

Finally, we can change current `third_party` directory structure into **(only considering docker implementation)**:

```
- `${TARGETPLATFORM}`
  - outline-ss-server (binary)
  - prometheus (binary)

// respect current directory structures
- outline-ss-server
  - LICENSE
  - METADATA
- prometheus
  - LICENSE
  - METADATA
- shellcheck (keep original as it is not required at build process)
```

> I agree that this implementation is not completed and should not be used as only works for docker.

## Using `$(uname -m)`

Or if we target both docker way and non-docker way building, I think it's reasonable to change directory structure into:

```bash
- $([[ "$(uname -s)" == "Darwin" ]] && echo "macos" || echo "linux")
  - $(uname -m) # For ARM, it should be arm64 if Apple based, otherwise aarch64
    - outline-ss-server
    - prometheus

: '
- linux
  - x86_64
  - aarch64
  - aarch32? (I could not check it)
- macos
  - x86_64
  - arm64
'
```

- [StackOverflow: Answer of Differences between arm64 and aarch64](https://stackoverflow.com/a/31852003)

Also, modify the build script.

> We still need additional changes for docker builds.

```bash
# Install third_party dependencies
readonly OS="$([[ "$(uname)" == "Darwin" ]] && echo "macos" || echo "linux")"
## Addition: check arch
readonly ARCH="$(uname -m)"
readonly BIN_DIR="${OUT_DIR}/bin"
mkdir -p "${BIN_DIR}"
cp "${ROOT_DIR}/third_party/prometheus/${OS}/${ARCH}/prometheus" "${BIN_DIR}/"
cp "${ROOT_DIR}/third_party/outline-ss-server/${OS}/${ARCH}/outline-ss-server" "${BIN_DIR}/"
```

I believe we can make even more simple by modifying build script located in `/src/shadowbox/server/build.action.sh`.

## Ref

- My way to build multi-platform outline-server image (using docker buildx): https://github.com/seia-soto/outline-server-multiarch

----

I am not an expert to the development and want to hear your opinion to this proposal! 👏

**Comment by seia-soto** [comment]
I've made some changes on my fork to use Buildx and you can compare to `master` branch from following URL: https://github.com/Jigsaw-Code/outline-server/compare/master...seia-soto:add-multiarch-support

However, still I need to figure out how to use Travis CI to test this. I almost don't have any knowledge of the mechanism of Outline-Server's TravisCI script.

**Comment by seia-soto** [comment]
For reference, the following output shows the result of Linux `uname` command on GitHub Actions.
It's better to include specific `armv6` build but I don't know why output of the command on `linux/arm/v6` is `armv7l`.

```
#10 [linux/arm64 2/2] RUN uname -a
#10 0.719 Linux buildkitsandbox 5.11.0-1027-azure #30~20.04.1-Ubuntu SMP Wed Jan 12 20:56:50 UTC 2022 aarch64 Linux
#10 DONE 0.7s

#13 [linux/amd64 2/2] RUN uname -a
#13 0.638 Linux buildkitsandbox 5.11.0-1027-azure #30~20.04.1-Ubuntu SMP Wed Jan 12 20:56:50 UTC 2022 x86_64 Linux
#13 DONE 0.7s

#14 [linux/arm/v7 2/2] RUN uname -a
#14 0.707 Linux buildkitsandbox 5.11.0-1027-azure #30~20.04.1-Ubuntu SMP Wed Jan 12 20:56:50 UTC 2022 armv7l Linux
#14 DONE 0.8s

#12 [linux/arm/v6 2/2] RUN uname -a
#12 0.752 Linux buildkitsandbox 5.11.0-1027-azure #30~20.04.1-Ubuntu SMP Wed Jan 12 20:56:50 UTC 2022 armv7l Linux
#12 DONE 0.8s
```

<details>
<summary>Files to test</summary>

**/Dockerfile**

```dockerfile
FROM alpine:latest

RUN uname -a
```

**/.github/workflows/test.yml**

```yml
name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        run: |
          docker buildx build \
            --platform="linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6" \
            --force-rm \
            --file Dockerfile \
            --tag "test" \
            .
```
</details>
